### ISSUE TITLE
code processors, object processors

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/dir#14]
The traditional flow is : 

```mermaid
graph TD;
    Code-in-scripts --> |source| Objects-in-package
```

But we can have: 

```mermaid
graph TD;
    Code-in-scripts --> |code-processor| Processed-code --> |source| Unprocessed-Objects --> |object-processor| Objects-in-package
```

Funnily enough the code doesn't need to be syntactic, we can easily extend R by forking from https://github.com/REditorSupport/vscode-R/blob/master/syntax/r.json 

Maybe the code processor should handle the code selection too (right now, pick all R files, recursive or not, and exclude some prefixes).

And I believe the natural input for a code processor is a list of files + some simple arguments, and the natural input for an object processor is a list of objects + some simple arguments.

With the code processor we can do #10 and everything discussed in https://x.com/jdatap/status/1910275123652763699

With the object processor (and a bit of code processing too) we can do #3 (the file name is in `attr(attr(fun, "srcref"), "srcfile")$filename`,  but we need other annotations)

So this fits really well the YAML format.

We can easily chain processors with YAML too, so we can modularize all the steps.

**Comment by moodymudskipper** [comment]
It's not even "Code" at the top, it's any file, doesn't even have to flat files.

We need better names. And examples for every step.

We don't have to provide steps for both dev and pkg when they are the same, we can have an inheritance system.

We can use a temp location to source preprocessed code rather than memory, will work better with existing tools.

The default would be:

```yaml
in_place_preprocessor: identity_in_place_preprocessor # arg-less fun, doesn't return anythin
virtual_preprocessor : identity_virtual_preprocessor # arg-less fun, returns a pkg dir to source from
# is there several ways to source? prob not. Sourcing is implicit and returns an env (or 2: for pkg and env)
# might have other side effects, user is responsible for those
state_processor : identity_state_processor # turns this env into a list of obj, + other state modifs if relevant
```
